[package]
name = "zk-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10", default-features = false }
